version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smk-inventory
    ports:
      - "8003:80"
    volumes:
      - ./:/var/www/html:cached              
      - /var/www/html/vendor               
      - /var/www/html/storage                
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    command: >
      bash -c "
      composer install --no-interaction --prefer-dist &&
      chown -R www-data:www-data storage bootstrap/cache &&
      chmod -R 775 storage bootstrap/cache &&
      chown -R www-data:www-data storage/logs &&
      chmod -R 775 storage/logs &&
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan view:cache &&
      apache2-foreground
      "
    restart: unless-stopped
    networks:
      - shared

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.cron
    container_name: smk-inventory-scheduler
    restart: unless-stopped
    volumes:
      - ./:/var/www/html:cached
      - /var/www/html/vendor
    command: >
      bash -c "
      composer install --no-interaction --prefer-dist --optimize-autoloader &&
      cron -f
      "
    depends_on:
      - app
    networks:
      - shared


networks:
  shared:
    external: true